# Generated by Django 4.1.3 on 2022-12-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='imagen',
        ),
    ]
