# Generated by Django 4.1.3 on 2022-12-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_remove_destino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
