# Generated by Django 4.1.3 on 2023-01-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_destino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='tiulo_imagen',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
