# Generated by Django 4.1.3 on 2023-01-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_destino_tiulo_imagen_alter_destino_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
