# Generated by Django 4.1.3 on 2023-01-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_destino_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='tiulo_imagen',
            new_name='tiuloimagen',
        ),
    ]
