# Generated by Django 4.1.3 on 2023-01-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_destino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='tiuloimagen',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
