# Generated by Django 4.1.3 on 2023-01-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_alter_destino_options_destino_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={},
        ),
        migrations.RemoveField(
            model_name='destino',
            name='updated',
        ),
    ]
