# Generated by Django 4.1.3 on 2023-01-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_alter_destino_options_remove_destino_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='tiuloimagen',
        ),
    ]
