# Generated by Django 4.1.3 on 2023-01-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_remove_destino_tiuloimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
