# Generated by Django 4.1.3 on 2023-01-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_alter_destino_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='destino',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
