# Generated by Django 4.1.3 on 2023-01-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0016_alter_destino_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='cuerpo',
            field=models.CharField(max_length=5000),
        ),
    ]
