# Generated by Django 4.1.3 on 2023-01-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
